C++17: Work-Around NVCC gatherParticles
The `noexcept` lambda does not compile in C++17 mode due to an NVCC
compiler bug, at least in NVCC 11.3.109.

Compiles in C++14 mode with the same compiler.

Error:
```
nvcc_internal_extended_lambda_implementation:732:77: error: ‘operator()’ is not a member of ‘int (ParticleBoundaryBuffer::gatherParticles(MultiParticleContainer&, const amrex::Vector<const amrex::MultiFab*>&)::<lambda(const SrcData&, int)>::*)(const amrex::ConstParticleTileData<0, 0, 4, 0>&, int) const noexcept’
Source/Particles/ParticleBoundaryBuffer.cpp: In member function ‘void ParticleBoundaryBuffer::gatherParticles(MultiParticleContainer&, const amrex::Vector<const amrex::MultiFab*>&)’:
Source/Particles/ParticleBoundaryBuffer.cpp:245:34: error: no matching function for call to ‘__nv_hdl_create_wrapper_t<false, false, __nv_dl_tag<void (ParticleBoundaryBuffer::*)(MultiParticleContainer&, const amrex::Vector<const amrex::MultiFab*>&), &ParticleBoundaryBuffer::gatherParticles, 1>, const GetParticlePosition, amrex::Array4<const float>, amrex::GpuArray<float, 3>, amrex::GpuArray<float, 3> >::__nv_hdl_create_wrapper(ParticleBoundaryBuffer::gatherParticles(MultiParticleContainer&, const amrex::Vector<const amrex::MultiFab*>&)::<lambda(const SrcData&, int)>, const GetParticlePosition&, amrex::Array4<const float>&, amrex::GpuArray<float, 3>&, amrex::GpuArray<float, 3>&)’
  245 |                     },
      |                                  ^
```