Resampling Trigger: Missing Include
AMReX update triggered missing include:
```
Source/Particles/Resampling/ResamplingTrigger.H(42):
error: namespace "amrex" has no member "Real"
```