Summit/PPC64le: Numpy 1.19.0
The latest (default) numpy, release `1.20.3` fails to build with fancy compiler errors of the form
```
error: "AltiVec argument passed to unprototyped function"
```

Thus, recommend an older numpy release to user that actually builds: `1.19.0`