extern 'C': Only in Headers (#2624)
* extern 'C': Only in Headers

This does not belong in source files.

Seen as missing symbols on CI for macOS and Intel, both clang compiles.

```
  File "/usr/local/lib/python3.9/site-packages/pywarpx/_libwarpx.py", line 94, in <module>
    from ._libwarpx import *
  File "/usr/local/lib/python3.9/site-packages/pywarpx/_libwarpx.py", line 94, in <module>
    libwarpx.warpx_Real_size.restype = ctypes.c_int
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    libwarpx.warpx_Real_size.restype = ctypes.c_int
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7f89a3edb820, warpx_Real_size): symbol not found
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fe5d36c5190, warpx_Real_size): symbol not found

AttributeError: /home/runner/.local/lib/python3.8/site-packages/pywarpx/libwarpx.3d.so: undefined symbol: warpx_Real_size
```

Refs.:
- https://stackoverflow.com/questions/2168241/is-it-required-to-add-extern-c-in-source-file-also
- https://isocpp.org/wiki/faq/mixing-c-and-cpp#call-cpp

* Fix: Declare amrex_init_with_inited_mpi

AMReX mocks out MPI anyway in serial builds.

* Wrapper: Add Missing Declarations

- fields
- PML fields

* Wrapper: More Missing Declarations

- `warpx_getCellSize`