Spectral: Missing Include
Fix a build error with the latest AMReX version due to a missing
include:
```
./Source/FieldSolver/SpectralSolver/SpectralKSpace.H:45:38:
error: ‘RealVect’ in namespace ‘amrex’ does not name a type
       const amrex::RealVect realspace_dx );
```